# Generated by Django 4.0.5 on 2022-06-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='Question',
        ),
    ]
